# Railway configuration for Magic Card Scanner
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/api/environment"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
ENV_MODE = "production"
PORT = "8000"

[environments.staging]
ENV_MODE = "staging"
PORT = "8000" 